twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        images_directory: '%relative_images_directory%'
        posts_images_directory: '%relative_posts_images_directory%'